// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5yGxQxAABhdAuXDkYzZhtJrHG5s-6CwE',
    appId: '1:523530686003:web:5a84deac43d4b3bcb6dd46',
    messagingSenderId: '523530686003',
    projectId: 'volt-guard-cbe72',
    authDomain: 'volt-guard-cbe72.firebaseapp.com',
    storageBucket: 'volt-guard-cbe72.firebasestorage.app',
    measurementId: 'G-B6HEB79B83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRdhZlU2s5hM3qXkEr0-px3mwheYIXLUk',
    appId: '1:523530686003:android:9cd70e5127d3db88b6dd46',
    messagingSenderId: '523530686003',
    projectId: 'volt-guard-cbe72',
    storageBucket: 'volt-guard-cbe72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2LYMSW1I-Hl9teMqHr8S1-mxBYT9zUvk',
    appId: '1:523530686003:ios:fc09a177af170973b6dd46',
    messagingSenderId: '523530686003',
    projectId: 'volt-guard-cbe72',
    storageBucket: 'volt-guard-cbe72.firebasestorage.app',
    iosBundleId: 'com.example.voltGuardTrue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2LYMSW1I-Hl9teMqHr8S1-mxBYT9zUvk',
    appId: '1:523530686003:ios:fc09a177af170973b6dd46',
    messagingSenderId: '523530686003',
    projectId: 'volt-guard-cbe72',
    storageBucket: 'volt-guard-cbe72.firebasestorage.app',
    iosBundleId: 'com.example.voltGuardTrue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5yGxQxAABhdAuXDkYzZhtJrHG5s-6CwE',
    appId: '1:523530686003:web:31290c52dcfe23f5b6dd46',
    messagingSenderId: '523530686003',
    projectId: 'volt-guard-cbe72',
    authDomain: 'volt-guard-cbe72.firebaseapp.com',
    storageBucket: 'volt-guard-cbe72.firebasestorage.app',
    measurementId: 'G-0QW6EN0G5N',
  );
}
